### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by Raiden38** [cpeuschel/streamdeck-octodeck#2]
So I added the plugin in my streamdeck, added the url (tried with http://octopi.local and with http://192.168.0.89) and Added either the global api key or an application api key, I only get that blue background without any text. Is there a way to troubleshoot that?

**Comment by cpeuschel** [comment]
Hi,

With the new Version its possible to debug the Plugin. You can enable the debugging mode here https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging

**Comment by mbravorus** [comment]
![image](https://user-images.githubusercontent.com/593723/132007926-c3510fc0-ce3a-4f3e-9d10-60a502650cc4.png)

I have used the debugging screen and I see that my OctoPrint is successfully replying, however nothing at all is being displayed on the button

**Comment by mbravorus** [comment]
and no, I am not concerned about the API key being visible, this is on an internal network and will be regenerated later anyway, thank you

**Comment by mnemonic83** [comment]
I had the same problem. Try removing the custom title you have entered in Stream Deck and the percentage/status should appear. Good luck!

**Comment by mbravorus** [comment]
I can confirm the problem is indeed resolved. Thanks for the tip.
